name: harlowe_chat_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  dio: ^5.4.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_chat_ui: ^1.6.4
  collection: ^1.18.0
  hive: ^2.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

